#!/bin/bash

#Command to make script universal in linux command line is -> export PATH=$PATH:~/local/bin/runCoodleSpringServicev1
#Change to your home directory
cd $home

#Run war project 
java -jar Github/Coodle/University-Academy-Web-Application-Spring-React/Back-End-SpringBoot-Server/Coodle/target/Coodle.war
